# Generated by Django 2.2.3 on 2019-09-04 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='部门编码')),
                ('name', models.CharField(default='', max_length=100, verbose_name='部门名称')),
                ('tel', models.CharField(default='', max_length=20, verbose_name='部门电话')),
                ('leader', models.CharField(default='', max_length=20, verbose_name='负责人')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='部门描述')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departs', to='common.Department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '管理部门',
                'verbose_name_plural': '管理部门',
            },
        ),
        migrations.CreateModel(
            name='Highway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='高速编号')),
                ('name', models.CharField(default='', max_length=100, verbose_name='高速公路全称')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='高速公路描述')),
                ('stake_mark_start', models.CharField(default='', max_length=20, verbose_name='起始桩号')),
                ('stake_mark_end', models.CharField(default='', max_length=20, verbose_name='结束桩号')),
                ('mileage', models.FloatField(default=0.0, verbose_name='里程数(公里)')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '高速公路',
                'verbose_name_plural': '高速公路',
            },
        ),
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='隧道编码')),
                ('name', models.CharField(default='', max_length=100, verbose_name='隧道名称')),
                ('category', models.IntegerField(choices=[(0, '短隧道 <=500M'), (1, '中长隧道 500~1000M'), (2, '长隧道 1000~3000M'), (3, '特长隧道 >3000M')], verbose_name='隧道类型')),
                ('left_mileage', models.IntegerField(default=0, verbose_name='左洞长度')),
                ('right_mileage', models.IntegerField(default=0, verbose_name='右洞长度')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='隧道描述')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnels', to='common.Department', verbose_name='所属部门')),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnels', to='common.Highway', verbose_name='所属高速')),
            ],
            options={
                'verbose_name': '隧道',
                'verbose_name_plural': '隧道',
            },
        ),
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='收费站编码')),
                ('name', models.CharField(default='', max_length=100, verbose_name='收费站名称')),
                ('category', models.IntegerField(choices=[(0, '匝道收费站'), (1, '省界收费站')], verbose_name='收费站类型')),
                ('line_entry_num', models.IntegerField(default=0, verbose_name='入口车道数')),
                ('line_exit_num', models.IntegerField(default=0, verbose_name='出口车道数')),
                ('leader', models.CharField(default='', max_length=20, verbose_name='负责人')),
                ('tel', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('stake_mark', models.CharField(default='', max_length=20, verbose_name='桩号')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='收费站描述')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolls', to='common.Department', verbose_name='所属部门')),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolls', to='common.Highway', verbose_name='所属高速')),
            ],
            options={
                'verbose_name': '收费站',
                'verbose_name_plural': '收费站',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='服务区编码')),
                ('name', models.CharField(default='', max_length=100, verbose_name='服务区名称')),
                ('stake_mark', models.CharField(default='', max_length=20, verbose_name='桩号')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='服务区描述')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='common.Department', verbose_name='所属部门')),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='common.Highway', verbose_name='所属高速')),
            ],
            options={
                'verbose_name': '服务区',
                'verbose_name_plural': '服务区',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='路段编号')),
                ('name', models.CharField(default='', max_length=100, verbose_name='路段全称')),
                ('line_num', models.IntegerField(default=4, verbose_name='车道数')),
                ('stake_mark_start', models.CharField(default='', max_length=20, verbose_name='起始桩号')),
                ('stake_mark_end', models.CharField(default='', max_length=20, verbose_name='结束桩号')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='common.Highway', verbose_name='所属高速')),
            ],
            options={
                'verbose_name': '高速路段',
                'verbose_name_plural': '高速路段',
            },
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='桥梁编码')),
                ('name', models.CharField(default='', max_length=100, verbose_name='桥梁名称')),
                ('category', models.IntegerField(choices=[(0, '小桥 8~30M'), (1, '中桥 30~100M'), (2, '大桥 100~1000M'), (3, '特大桥 >1000M')], verbose_name='桥梁类型')),
                ('mileage', models.IntegerField(default=0, verbose_name='桥梁长度')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='桥梁描述')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridges', to='common.Department', verbose_name='所属部门')),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridges', to='common.Highway', verbose_name='所属高速')),
            ],
            options={
                'verbose_name': '桥梁',
                'verbose_name_plural': '桥梁',
            },
        ),
    ]
