# Generated by Django 2.2.3 on 2019-09-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190904_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highway',
            name='code',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='高速编号'),
        ),
    ]
