# Generated by Django 2.2.3 on 2019-09-04 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(default='', max_length=255, verbose_name='通讯参数')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='参数描述')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '通讯参数',
                'verbose_name_plural': '通讯参数',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='请输入类型名称', max_length=30, verbose_name='类型名称')),
                ('code', models.CharField(default='', help_text='请输入类型代码', max_length=30, verbose_name='类型代码')),
                ('desc', models.CharField(default='', help_text='请输入类型描述', max_length=200, verbose_name='类型描述')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent', models.ForeignKey(blank=True, help_text='请选择父级类型', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='device.DeviceType', verbose_name='父级类型')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='请输入设备名', max_length=100, verbose_name='设备名称')),
                ('code', models.CharField(default='', help_text='请输入设备编码', max_length=100, verbose_name='设备编码')),
                ('stake_mark', models.CharField(default='', help_text='请输入桩号', max_length=20, verbose_name='桩号')),
                ('coordinate', models.CharField(default='', max_length=20, verbose_name='显示坐标')),
                ('longitude', models.FloatField(default=0.0, verbose_name='经度')),
                ('latitude', models.FloatField(default=0.0, verbose_name='纬度')),
                ('Highway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Highway', verbose_name='所属高速')),
                ('comm_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.CommInfo', verbose_name='通讯参数')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Department', verbose_name='管理单位')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='device.DeviceType', verbose_name='设备类型')),
            ],
        ),
    ]
